Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcSimpleMusicSite_CourseProject.Models;
using System.IO;
using System.Web.Security;
using MvcSimpleMusicSite_CourseProject.Helpers;

namespace MvcSimpleMusicSite_CourseProject.Controllers
{
    public class MusicController : Controller
    {
        private readonly IGenreRepository genreRepository;
        private readonly IArtistRepository artistRepository;
        private readonly ITrackRepository trackRepository;
        private readonly IAlbumRepository albumRepository;
        private readonly ILikeRepository likeRepository;
        private readonly ILikeRepository listenedRepository;
        private readonly IDowloadRepository dowloadRepository;

        const int UnoMb = 1048576;

        public MusicController(IGenreRepository genreRepository,
            IArtistRepository artistRepository,
            ITrackRepository trackRepository,
            IAlbumRepository albumRepository,
            ILikeRepository likeRepository,
            ILikeRepository listenedRepository,
            IDowloadRepository dowloadRepository)
        {
            this.genreRepository = genreRepository;
            this.artistRepository = artistRepository;
            this.trackRepository = trackRepository;
            this.albumRepository = albumRepository;
            this.likeRepository = likeRepository;
            this.listenedRepository = listenedRepository;
            this.dowloadRepository = dowloadRepository;
        }


        [HttpPost]
        public void Upload()
        {
            UploadedFile file = RetrieveFileFromRequest();

            SaveFile(file);
        }

        private UploadedFile RetrieveFileFromRequest()
        {            
            byte[] fileContents = null;

            if (Request.Files.Count > 0)
            {  
                var file = Request.Files[0];
                fileContents = new byte[file.ContentLength];
                file.InputStream.Read(fileContents, 0, file.ContentLength);                
            }
            else 
                if (Request.ContentLength > 0)
            {                
                fileContents = new byte[Request.ContentLength];
                Request.InputStream.Read(fileContents, 0, Request.ContentLength);                 
            }

            return new UploadedFile()
            {                
                FileSize = fileContents != null ? fileContents.Length : 0,
                Contents = fileContents
            };
        }

        private ActionResult SaveFile(UploadedFile file)
        {
            System.IO.FileStream stream = null;

            string filePath = null;

            string name = null;

            try
            {

                name = DateTime.Now.Ticks + ".mp3";

                filePath = Path.Combine(Server.MapPath("~/Content/UploadingMusic"), name);

                stream = new FileStream(filePath, FileMode.Create, FileAccess.Write);

                if (stream.CanWrite)
                {
                    stream.Write(file.Contents, 0, file.Contents.Length);
                }
            }
            finally
            {
                if (stream != null)
                {
                    stream.Close();
                }
            }

            WritinginDb(filePath, name);

            return RedirectToAction("Index", "Site");
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase[] fileUpload)
        {
            if (null == fileUpload[0] || fileUpload.Count() == 0)
            {
                return View();
            }

            foreach (var item in fileUpload)
            {
                string name = DateTime.Now.Ticks.ToString() + ".mp3";

                string filePath = Path.Combine(Server.MapPath("~/Content/UploadingMusic"), name);

                item.SaveAs(filePath);

                WritinginDb(filePath, name);

            }

            return RedirectToAction("Index", "Site");
        }

        public void WritinginDb(string filePath, string name)
        {
            TagLib.File tl = TagLib.File.Create(filePath);

            string artist = tl.Tag.FirstArtist == "" || tl.Tag.FirstArtist == null ? "Unknow" : tl.Tag.FirstArtist;

            string title = tl.Tag.Title == "" || tl.Tag.Title == null ? "Unknow" : tl.Tag.Title;

            string album = tl.Tag.Album == "" || tl.Tag.Album == null ? "Unknow" : tl.Tag.Album;

            string genre = tl.Tag.FirstGenre == "" || tl.Tag.FirstGenre == null ? "Unknow" : tl.Tag.FirstGenre;

            artistRepository.InsertOrUpdate(artist);

            albumRepository.InsertOrUpdate(album, artist, tl.Tag.Year.ToString());

            genreRepository.InsertOrUpdate(genre);

            trackRepository.InsertOrUpdate(title,
                artist,
                genre,
                album,
                name,
                tl.Properties.Codecs.First().Duration.ToString(),
                tl.Properties.AudioBitrate.ToString(),
                ((double)(tl.InvariantEndPosition / UnoMb)).ToString());

            dowloadRepository.InsertOrUpdate(title);
        }

        public FileResult Send_Mp3(int Id)
        {
            Track trackForSend = trackRepository.Find(Id);

            string filePath = Server.MapPath("~/" + trackForSend.Mp3Url.Remove(0, 3));

            string fileType = "audio/mp3";

            string fileName = trackForSend.Album.Artist.Title + "_" + trackForSend.Title;

            return File(filePath, fileType, fileName);
        }

        public ActionResult Search(string searchContext, int IdGenre = 0)
        {
            IEnumerable<Track> result = null;

            if (IdGenre > 0)
            {
                result = genreRepository.Find(IdGenre).Tracks;

                return View(result);
            }

            IEnumerable<Track> resultTrack = trackRepository.Find(searchContext);

            IEnumerable<Artist> resultArtist = artistRepository.Find(searchContext);

            if (null != resultArtist && resultArtist.Count() > 0)
            {
                bool flag = true;

                foreach (var item in resultArtist)
                {
                    foreach (var _item in item.Albums)
                    {
                        if (flag)
                        {
                            result = _item.Tracks;
                            flag = !flag;
                            continue;
                        }
                        result = result.Concat(_item.Tracks);
                    }
                }
            }

            if (null != result)
                result = result.Concat(resultTrack);
            else
                result = resultTrack;

            //IEnumerable<Track> _result = null;

            //foreach (var item in result)
            //{
            //    if (_result.Where(t => t.Id == item.Id) == null)
            //    {
            //        _result.Concat((IEnumerable<Track>)item);
            //    }
            //}

            return View(result);
        }
    }
}

Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcSimpleMusicSite_CourseProject.Models;
using System.Globalization;
using System.Web.Security;

namespace MvcSimpleMusicSite_CourseProject.Controllers
{
    public class SiteController : Controller
    {
        private readonly ITrackRepository trackRepository;
        private readonly IGenreRepository genreRepository;
        private readonly IDowloadRepository downloadRepository;

        public SiteController(ITrackRepository trackRepository,
            IGenreRepository genreRepository,
            IDowloadRepository downloadRepository)
        {
            this.trackRepository = trackRepository;
            this.genreRepository = genreRepository;
            this.downloadRepository = downloadRepository;
        }
 
        public ViewResult Index()
        {
            return View(trackRepository.AllIncluding(
                track => track.Genre,
                track => track.Album.Artist,
                track => track.Likes,
                track => track.Dowloads,
                track => track.Listened)
                );
        }

        public ViewResult Details(int id)
        {
            ViewBag.User = downloadRepository.Find(id).UserName;
            return View(trackRepository.Find(id));
        }

        public ViewResult About()
        {
            return View();
        }

        public ActionResult SetCulture(string lang, string returnUrl)
        {

            Session["Culture"] = new CultureInfo(lang);

            return Redirect(returnUrl);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult TagCloud()
        {
            var genres = genreRepository.All;
            return Json(genres, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Shared/_LayoutExtended.cshtml
<!DOCTYPE html>
<html>
<head runat="server">
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap/css/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    @using MvcSimpleMusicSite_CourseProject.Resources.Views.Shared;
    @using MvcSimpleMusicSite_CourseProject.Resources.Views;
</head>
<body>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span10">
                <div class="row-fluid">
                    <div class="span8">
                        <img class = "border-radius" src="@Url.Content("~/Content/Images/_logo.jpg")" alt="" />
                    </div>
                    <div class="span4">
                        <div class="setting">
                            @{Html.RenderPartial("_SettingPartial");}
                        </div>
                        <div class="logOn">
                            @{Html.RenderPartial("_LogOnPartial");}
                        </div>         
                        
                        <div id = "diagramm" class = "diagramm">
                              
                        </div>                
                    </div>
                </div>
                <div class="row-fluid ">
                    <div class="span8">
                        @{Html.RenderPartial("_SearchFormPartial");}
                    </div>
                    <div>
                        <img id = "img_upload" src="@Url.Content("~/Content/Images/Progress.gif")" alt=""/>
                    </div>
                </div>
            </div>
            <div class="span2">
                <div class="tagcloud" id="3dcloud_block">
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span9">
                @RenderBody()
            </div>
            <div class="span3">
                <div class="well sidebar-nav">
                    <ul class="nav nav-tabs nav-stacked">
                        <li class="nav-header">Навигация</li>
                        <li>@Html.ActionLink(@CommonRes.ActionMainPage, "Index", "Site")</li>
                        <li>@Html.ActionLink(@CommonRes.ActionAboutPage, "About", "Site")</li>
                        <li class="nav-header">Действия</li>
                        <li>@Html.ActionLink(@PagesAndLayotsRes.UploadFile, "Create", "Music")</li>               
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="container">
            <div class="culture">
                <i>@PagesAndLayotsRes.Language</i>
            </div>
            <i>&copy slesh @( DateTime.Now.Year.ToString())</i>
        </div>
    </div>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-2.0.0.min.js")"></script>       
    <script type="text/javascript" src="@Url.Content("~/Content/scripts/dropdown.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/scripts/swfobject.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/scripts/scripts.js")"></script>                   
</body>
</html>

Views/Shared/_LogOnPartial.cshtml
@using MvcSimpleMusicSite_CourseProject.Resources.Views;
@using MvcSimpleMusicSite_CourseProject.Resources.Views.Shared;

<div class="navbar">
    <div class="nav-collapse collapse">
        @if (Request.IsAuthenticated)
        {     
            <p class="text-success">
                @CommonRes.Hello, <strong>@User.Identity.Name</strong> ! |
                @Html.ActionLink(@PagesAndLayotsRes.LogOff, "LogOff", "Account", new { area = "" }, null)
            </p>
        }
        else
        {
            <ul class="inline">
                <li class = "first">@Html.ActionLink(@PagesAndLayotsRes.LogOn, "LogOn", "Account", new { area = "" }, null)</li>
                <li>@Html.ActionLink(@PagesAndLayotsRes.Admin, string.Empty, string.Empty, new { area = "Admin" }, null)</li>
            </ul>
        }
    </div>
</div>

Views/Shared/_SearchFormPartial.cshtml
@using MvcSimpleMusicSite_CourseProject.Resources.Views.Shared;
@using MvcSimpleMusicSite_CourseProject.Resources.Views;
@using (Html.BeginForm("Search", "Music", FormMethod.Post))
{
    <div class="platform">
        <div class="input-append">
            <input class="span2" id="appendedInputButtons" type="text" name="searchContext" />
            <button class="btn btn-danger" type="submit">
                @CommonRes.Search</button>
        </div>
        <div>
            <i>@PagesAndLayotsRes.SearchMessage1
            <strong id = "artist"><a href = "#">Avril Lavigne</a></strong>
        @PagesAndLayotsRes.SearchMessage2 <strong id = "track"><a href = "#">Back in black</a></strong>
            </i>
        </div>
    </div>
}

Views/Shared/_SettingPartial.cshtml
@using MvcSimpleMusicSite_CourseProject.Resources.Views;
<ul class="nav">
    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">@PagesAndLayotsRes.Settings
        <b class="caret"></b></a>
        <ul id="ul" class="dropdown-menu">
            <li class="nav-header">@PagesAndLayotsRes.Themes</li>
            <li class="sunny"><a href="#">@PagesAndLayotsRes.Bricks</a></li>
            <li class="snowy"><a href="#">@PagesAndLayotsRes.Carbon</a></li>
            <li class="rainy"><a href="#">@PagesAndLayotsRes.VeryBlue</a></li>
            <li class="default"><a href="#">@PagesAndLayotsRes.Default</a></li>
            <li class="nav-header">@PagesAndLayotsRes.SelLan</li>
            <li>@Html.ActionLink("Русский", "SetCulture", "Site", new { lang = "ru", returnUrl = this.Request.RawUrl }, null)</li>
            <li>@Html.ActionLink("English", "SetCulture", "Site", new { lang = "en", returnUrl = this.Request.RawUrl }, null)</li>
        </ul>
    </li>
</ul>